import TAKE_GENERATOR_TYPES from './TAKE_GENERATOR_TYPES';

const TAKE_GENERATOR_TYPES_MAP = {
  takeLeading: TAKE_GENERATOR_TYPES.TAKE_LEADING,
  takeLatest: TAKE_GENERATOR_TYPES.TAKE_LATEST,
  takeEvery: TAKE_GENERATOR_TYPES.TAKE_EVERY,
  debounceHelper: TAKE_GENERATOR_TYPES.DEBOUNCE,
  throttle: TAKE_GENERATOR_TYPES.THROTTLE,
};

export default TAKE_GENERATOR_TYPES_MAP;
